**Задание на лабораторную работу №1**  
 Средствами numpy сгенерировать два вектора, транспонировать один из созданных векторов и найти их произведение.

> Замечание

При транспонировании вектора-строки функцией a.transpose() или a.T ничего не изменится. Вектор, как был строкой, так строкой и останется. Это происходит потому, что массив `a` имеет только одну размерность.
Самым простым способом транспонирования, является смена размерности:
`a.reshape(-1, 1)`
здесь -1 -- говорит NumPy вычислять размер автоматически

In [3]:
import numpy as np

#Создание генератора
rnd = np.random.default_rng()

# Генерация двух векторов
vector1 = rnd.integers(-10, 10, 5)
vector2 = rnd.integers(-10, 10, 5)

# Транспонирование первого вектора
vector1_T = vector1.reshape(-1, 1)

# Нахождение произведения
result = np.dot(vector1_T, vector2.reshape(1, -1))
result2 = np.outer(vector1_T, vector2)

print("Первый вектор:", vector1)
print("Второй вектор:", vector2)
print("\nТранспонированный первый вектор:")
print(vector1_T)
print("\nРезультат произведения векторов:")
print(result,"\n")
print(result2)

Первый вектор: [-9 -4  3  1  3]
Второй вектор: [-10  -7  -4   8   7]

Транспонированный первый вектор:
[[-9]
 [-4]
 [ 3]
 [ 1]
 [ 3]]

Результат произведения векторов:
[[ 90  63  36 -72 -63]
 [ 40  28  16 -32 -28]
 [-30 -21 -12  24  21]
 [-10  -7  -4   8   7]
 [-30 -21 -12  24  21]] 

[[ 90  63  36 -72 -63]
 [ 40  28  16 -32 -28]
 [-30 -21 -12  24  21]
 [-10  -7  -4   8   7]
 [-30 -21 -12  24  21]]
